package pl.ue.oops.game.universe.control;

public enum Signal {
    REQUESTED_UP_MOVEMENT,
    REQUESTED_DOWN_MOVEMENT,
    REQUESTED_LEFT_MOVEMENT,
    REQUESTED_SPAWN, REQUESTED_RIGHT_MOVEMENT,
    REQUESTED_LEFT_ATTACK,
    REQUESTED_RIGHT_ATTACK,
    REQUESTED_UP_ATTACK,
    REQUESTED_DOWN_ATTACK,
    REQUESTED_PASS, REQUESTED_SIDEWAYS_SPAWN;
}
